name: build

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache gradle
        uses: actions/cache@v2
        id: gradle
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-release-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-release-${{ hashFiles('**/*.gradle') }}

      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn
        with:
          path: ~/.npm/caches
          key: ${{ runner.os }}-release-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-release-

      - name: Install npm dependencies
        run: |
          yarn

      - name: Set up JDK 20
        uses: actions/setup-java@v1
        with:
          java-version: 20

      - name: Build Android Release
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
