name: build

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  # install-and-test:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install npm dependencies
  #       run: |
  #         yarn

  build-android:
    # needs: install-and-test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install npm dependencies
        run: |
          yarn

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build Android Release
        run: |
          npm run build:android

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
