name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     cache: 'npm'

      - name: Install npm dependencies
        run: |
          npm i

      - name: Cache gradle
        uses: actions/cache@v3
        id: gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-

      - name: Set up JDK 20
        uses: actions/setup-java@v1
        with:
          java-version: 20

      - name: Build Android Release
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: v0.0.1
          tag_name: v0.0.1
          files: android/app/build/outputs/apk/release/app-release.apk